version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - add_ssh_keys:
          fingerprints:
            - "98:ab:2b:30:60:00:82:86:bb:85:db:87:22:c4:4f:b1"
      - checkout
      # - run: systeminfo
      - run:
          name: "测试"
          shell: cmd.exe
          command: |
            testgit.bat